name: Pre-Commit Hooks

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Check
        run: |
          pre-commit run --all-files
